version: '3.3'

services:
  adguardhome:
    build: .
    container_name: adguardhome
    volumes:
      - /arespool/appdata/adguardhome/work:/opt/adguardhome/work
      - /arespool/appdata/adguardhome/conf:/opt/adguardhome/conf
      - /arespool/appdata/openvpn-configs:/etc/openvpn
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "853:853/tcp"
      - "3000:3000/tcp"
    restart: unless-stopped